version: '3.9'
services:
  client-backend:
    #    2 цифра - для общего, 3 для частности
    image: client:0.1.0
    build:
      context: ./backend-chat
      dockerfile: Dockerfile
    #      указываем расположение Dockerfile
    ports:
      - "8080:8080"
#     внешний:внутренний
    depends_on:
      - zookeeper-1
      - kafka-1

  #  client-frontend:
  #    image: front:0.0.5
  #    build:
  #      context: /frontend-chat
  #      dockerfile: Dockerfile
  #    ports:
  #      - '3000:3000'
  #    stdin_open: true
  #    tty: true # для открытия терминала после ст
  #    depends_on:
  #      - client-backend
  #


  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka-1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-1

    ports:
      - 29092:29092

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8090:8080"
#      внешний:внутренний
    depends_on:
    - kafka-1
    environment:
     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9092
     KAFKA_CLUSTERS_0_METRICS_PORT: 9997
     DYNAMIC_CONFIG_ENABLED: 'true'
